### ISSUE TITLE
Unexpected behaviour using issue view on Ubuntu, Zsh

### ISSUE THREAD

**Issue by asdf8601** [profclems/glab#636] opened 2021-03-05 08:04 UTC
**Description**

When I execute `glab issue view 4` the result doesn't allow me to use up/down neither  j/k keys. When I exit from that view by pressing q+Enter, I have to press ctrl-c as well to efectivily return to the prompt. This only happens with a specific issue.

**Expected Behavior vs Actual Behavior**

I assume that `less` (or another similar program) is executed by piping the content to them. So pressing j/k is correct the way to scrolling there.

**Possible Fix**

**Steps to Reproduce**

1. Type this `glab issue 4` (my issue)
2. View the output 
3. See error

<details>
<summary>Here is the content of my issue</summary>

## Description

```bash
$ dag foo
foo
├── /home
├── /home
├── /home
├── /home
├── /home
└── /home


$ dag foo
foo


$ dag foo
foo
├── /home/
├── /home/
├── /home/
├── /home/
└── /home/


$ dag foo
foo
├── /home/
├── /home/
├── /home/
├── /home/
├── /home/
└── /home/


$ dag foo
foo
├── /home/
└── /home/


$ dag foo
foo


$ dag foo
foo


$ dag foo
foo


$ dag foo
foo
├── /home/
├── /home/
├── /home/
├── /home/
└── /home/


$ dag foo
foo


$ dag foo
foo
├── /home/
└── /home/


$ dag foo
foo
└── /home/

```

## Traceback error

Paste here the complete traceback error, including the command executed.

## Versions

- foo
- foo (only for installation problems)
- foo (only for installation problems)
- foo (only for installation problems)

```bash
# Paste the folling and copy the complete output here
pip freeze | grep foo
python -V
pip -V
```

### Others

(Optionally include the versions of other software that may concern)

</details>

**Logs**

**Your Environment**

* Version used (Run `glab --version`): `glab version 1.15.0 (2021-02-15)`
* Operating System and version: `Linux  5.4.0-66-generic #74-Ubuntu SMP Wed Jan 27 22:54:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by zemzale** [comment] 2021-03-05 08:51
Thanks for reporting this @mmngreco 

I have encountered this issue too. The one thing I can say for sure that it doesn't affect list commands like `issue list`. There must be something different about how we do paging for those commands. I am gonna look into that.

**Comment by zemzale** [comment] 2021-03-05 09:16
I seems to have found the cause. Its something related of how we are rendering markdown(for the description).

When there is no markdown rendering involved, everything works as expected. I am gonna need more time to find a fix for this.

**Comment by asdf8601** [comment] 2021-03-05 15:25
Thanks for your quick response @zemzale! Fortunately, this issue is so specific that I can keep using  glab as usual! :-)

**Comment by profclems** [comment] 2021-03-08 20:45
> I seems to have found the cause. Its something related of how we are rendering markdown(for the description).
> 
> When there is no markdown rendering involved, everything works as expected. I am gonna need more time to find a fix for this.

I have noticed this as well... I can't really tell what's particularly wrong with our paging style right now

@mmngreco, can you check if the issue is the same when you also set the LESS environment variable to something like LESS=RX, or some other value that excludes F which we would otherwise set by default?

**Comment by zemzale** [comment] 2021-03-09 10:29
There seems to be a problem with `glamour` auto styles
https://github.com/profclems/glab/blob/f5ea29e4ac5bf664802a68b78c0b7c631c10fb20/pkg/utils/utils.go#L28-L40
If in this code block we don't use `glamour.WithEnvironmentConfig` there are no problems with printing. 

It seems that it's possible to reproduce this:
- in environment `PAGER=LESS` or similar
- don't have glamour environment variables 
- The system will try to resolve auto style and break the pager

If I explicitly use `glamour.WithStylePath("dark")` everything works normally.  

I did a bit of digging, and in my case `auto` value became `dark`. This made me confused because `glamour.WithStylePath("dark")` works just fine.

Did even more digging, `glamour` uses `termenv.HasDarkBackground` to check what is the background color and returns the appropriate style. If I remove the `HasDarkBackground` call from this resolver everything works just fine. 

At this point I don't wanna do any more digging into what exactly is being done there and why does it fail, but looks like we should resolve background color before we start the pager, and pass it explicitly, without using `glamour.WithEnvironmentConfig`

Note: I wanted to see how `gh` does this and seems that they have had similar pains: https://github.com/cli/cli/commit/ed4075517c42690668de1d50993787cbd86f3888

**Comment by zemzale** [comment] 2021-03-09 10:29
I will try to come up with a PR in the next few days to fix this.

**Comment by asdf8601** [comment] 2021-03-09 12:37
> @mmngreco, can you check if the issue is the same when you also set the LESS environment variable to something like LESS=RX, or some other value that excludes F which we would otherwise set by default?

Here's my default value:

```bash
$ echo $LESS
 -R
```

I experienced the same behaviour by executing the following lines.
I've also tried differents ways just to be sure ;-) 

```bash
$ LESS=RX glab issue show 5 
$ LESS=RX
$ glab issue show 5 
$ export LESS=RX
$ glab issue show 5
```

**Comment by zemzale** [comment] 2021-03-09 13:13
@mmngreco Could you please try running `GLAMOUR_STYLE=dark glab issue view 5` or (or `GLAMOUR_STYLE=light glab issue view 5` depending on your color scheme). 

Can you confirm that the issue goes away?

**Comment by asdf8601** [comment] 2021-03-09 13:20
> Can you confirm that the issue goes away? 

Wonderful, this works like a charm!

**Closed as completed** 2021-03-11 14:54 UTC
Labels: bug, priority: medium
