### ISSUE TITLE
Glab binary installed in incorrect location for .deb installers

### ISSUE THREAD

**Issue by iggyvolz** [profclems/glab#587] opened 2021-01-25 14:27 UTC
**Description**
When installing version 1.13.1 from the .deb installer, the binary is installed to /usr/local/bin/bin/glab instead of /usr/local/bin/glab.

**Expected Behavior vs Actual Behavior**
```
$ dpkg --contents glab_1.13.1_Linux_x86_64.deb
# Actual:
drwxr-xr-x 0/0               0 2020-12-28 17:22 ./usr/
drwxr-xr-x 0/0               0 2020-12-28 17:22 ./usr/local/
drwxr-xr-x 0/0               0 2020-12-28 17:22 ./usr/local/bin/
drwxr-xr-x 0/0               0 2020-12-28 17:22 ./usr/local/bin/bin/
-rwxr-xr-x 0/0        19165184 2020-12-28 17:22 ./usr/local/bin/bin/glab
# Expected:
drwxr-xr-x 0/0               0 2020-12-28 17:22 ./usr/
drwxr-xr-x 0/0               0 2020-12-28 17:22 ./usr/local/
drwxr-xr-x 0/0               0 2020-12-28 17:22 ./usr/local/bin/
-rwxr-xr-x 0/0        19165184 2020-12-28 17:22 ./usr/local/bin/glab
```

**Possible Fix**
Need to move the `glab` binary up one level.  Doesn't appear to affect any of the other packages.

**Steps to Reproduce**
```sh
$ wget https://github.com/profclems/glab/releases/download/v1.13.1/glab_1.13.1_Linux_x86_64.deb
$ dpkg --contents glab_1.13.1_Linux_x86_64.deb
# Alternatively:
$ apt install ./glab_1.13.1_Linux_x86_64.deb
$ which glab
# Nothing.
$ find /usr/local/bin -name glab
/usr/local/bin/bin/glab
```

**Your Environment**
* Version used (Run `glab --version`): glab version 1.13.1 (2020-12-28)
* Operating System and version: Ubuntu 20.04

**Comment by profclems** [comment] 2021-01-25 14:50
Thanks a lot @iggyvolz for reporting this issue!

This seems to be a duplicate of #508 which has been resolved by #512 and it is pending release.

I will be releasing v1.14.0 tomorrow.

**Closed as completed** 2021-01-25 14:52 UTC
Labels: bug, duplicate
