### ISSUE TITLE
glab repo clone requires to be run in a git directory

### ISSUE THREAD

**Issue by profclems** [profclems/glab#198] opened 2020-09-04 11:32 UTC
```sh
$ glab repo clone test
test

Could not find remote url for gitlab in remote.origin.url
Possible errors:
- This directory may not be a git repository

Possible Fix:
- Make sure the directory is a git repository
- Run glab config -g --remote-var=<name>
NB: change <name> to the shorthand name.
```
The command should work outside a git directory as well

**Comment by andhe** [comment] 2020-09-06 15:29
Looks like the call chain for this is:
`repo clone ... -> currentUser() -> git.InitGitlabClient() -> GetRepo() -> GetRemoteURL()`

The currentUser() call was introduced in commit 3ec2810c44b2971151e58ed132c7bdac968f08c9 (which likely caused the regression).

(Note however that currentUser() is not the only caller of git.InitGitlabClient() in this code, so simply eliminating it does not fix the problem. Several, if not all, of the callers seems to be introduced in the same commit as pointed out before though.)

**Comment by andhe** [comment] 2020-09-06 15:48
A general design comment is that  glab seems to be way to keen on calling log.Fatal* or os.Exit deep down in library or helper methods. It would be better if they would just return err instead and let higher level code deal with it (or atleast give them a chance to clean up). This would require a major refactoring/cleanup that ofcourse isn't suitable just as a fix for this bug.

A minor nitpick is that in internal/git/git.go GetRemoteURL an error message is printed (using fmt.Println instead of log.Fatal*) then calls os.Exit(0). The exit code should definitely not be 0 (success!) when glab exists because of an error.

**Comment by profclems** [comment] 2020-09-06 15:54
I just thought so too... I perfectly agree with this point. I thought of doing a major refactoring to introduce some consistencies when there are no active PRs.

**Comment by andhe** [comment] 2020-09-11 20:56
Looked at how to avoid triggering the fatal getRepo function in a minimalistic way. Given that both calls to git.InitiGitlabClient ignores the second returned argument anyway, the result in it should not matter. If the first argument passed into InitGitlabClient is set to false, that avoids the fatal code-path which also just modifies the second return argument (which we deemed did not matter)... Is this good enough? I can after this do `cd /tmp && glab repo clone glab-cli/test foo123` successfully atleast.

```
diff --git a/commands/project.go b/commands/project.go
index 11e7b92..d52a01f 100644
--- a/commands/project.go
+++ b/commands/project.go
@@ -7,7 +7,7 @@ import (
 )
 
 func getProject(projectID interface{}) (*gitlab.Project, error) {
-       gitlabClient, _ := git.InitGitlabClient()
+       gitlabClient, _ := git.InitGitlabClient(false)
        opts := &gitlab.GetProjectOptions{
                Statistics:           gitlab.Bool(true),
                License:              gitlab.Bool(true),
diff --git a/commands/user.go b/commands/user.go
index 3d8df20..f2d70df 100644
--- a/commands/user.go
+++ b/commands/user.go
@@ -9,7 +9,7 @@ import (
 )
 
 func currentUser() (string, error) {
-       gLab, _ := git.InitGitlabClient()
+       gLab, _ := git.InitGitlabClient(false)
        u, _, err := gLab.Users.CurrentUser()
        if err != nil {
                return "", err

```

**Closed as completed** 2020-09-11 21:21 UTC
Labels: bug

**Comment by profclems** [comment] 2020-09-13 18:06
Thanks @andhe, have you considered any optimal alternative solution??
The alternative solution I can think of is to initialize the GitLab client directly without calling git.InitGitlabClient() but that isn't a consistent solution imao
